name: Alex App Version Action
on:
  # Trigger the workflow on push request,
  # but only for the master branch
  push:
    branches:
      - master
      - dev

jobs:
  Version-check:
    runs-on: ubuntu-latest
    name: Increment Tag Version
    steps:
    - name: Increment version
      id: version
      uses: perfectpattern/IncrementGithubAction@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
